package org.romecraft.RomeChat;

import java.util.logging.Logger;

import org.bukkit.event.Listener;
import org.bukkit.event.player.AsyncPlayerChatEvent;

public abstract class RomeChatPlayerListener implements Listener {
	
	protected static final Logger logger = Logger.getLogger("Minecraft");
	
	public void onPlayerChat(final AsyncPlayerChatEvent event) {
		
	}
	
	public String getChatType(final String message)
	{
		if (message.length() == 0)
		{
			//Ignore empty chat events generated by plugins
			return "";
		}
		
		final String prefix = message.substring(0, 3);
		
		if (prefix.equals("/w ")) {	return "shout"; }
		
		else if (prefix.equals("/y ")) { return "yell"; }
		
		else if (prefix.equals("/me")) { return "action"; }
		
		else { return ""; }
	}
}
